variables:
- group: DotNet-HelixApi-Access # TODO: make available internally only
- name: _BuildConfig
  value: Release
- name: _BuildArgs
  value: /p:OfficialBuildId=$(Build.BuildNumber)
         /p:ArcadeBuild=true


jobs:
- template: /eng/common/templates/job/job.yml
  parameters:
    name: build_linux
    displayName: Build linker on linux
    enableTelemetry: true
    pool:
      'Hosted Ubuntu 1604' # available on internal and public. recommended for both.
    # enablePublishTestResults
    # Publish build logs to pipeline storage
    enablePublishBuildArtifacts: true
    helixRepo: 'mono/linker'
    steps:
    - checkout: self
      submodules: true
    - script: eng/common/cibuild.sh --projects $(Build.SourcesDirectory)/illink.sln
              --configuration $(_BuildConfig) $(_BuildArgs)

- template: /eng/common/templates/job/job.yml
  parameters:
    name: build_windows
    displayName: Build linker on windows
    enableTelemetry: true
    enableMicrobuild: true
    pool:
      'dotnet-internal-temp' # internal
      # for public, need to use 'Hosted VS2017'
    # publish asset manifests to pipeline storage (only for legs that publish)
    enablePublishBuildAssets: true
    enablePublishBuildArtifacts: true
    helixRepo: 'mono/linker'
    variables:
    - group: DotNet-Blob-Feed
    - _DotNetPublishToBlobFeed: true
    # required by microbuild install step
    - _TeamName: .NET
    # DotNetSignType needs to be passed for arcade signing targets, otherwise it defaults to real.
    # _SignType is used in the arcade templates that install microbuild.
    - DotNetSignType: $(_SignType)
    steps:
    - checkout: self
      submodules: true
    - script: eng\common\cibuild.cmd -projects $(Build.SourcesDirectory)\illink.sln
              -configuration $(_BuildConfig) $(_BuildArgs)
              /p:DotNetPublishToBlobFeed=$(_DotNetPublishToBlobFeed)
              /p:DotNetPublishBlobFeedUrl=https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
              /p:DotNetPublishBlobFeedKey=$(dotnetfeed-storage-access-key-1)