pool:
  vmImage: 'Ubuntu-16.04'

jobs:
- template: /eng/common/templates/job/job.yml
  parameters:
    name: build
    displayName: Build linker
    enableTelemetry: true
    enableMicrobuild: true
    pool:
      dnceng-linux-internal-temp
    # Publish asset manifests to pipeline storage
    enablePublishBuildAssets: true
    # enablePublishTestResults
    # enablePublishBuildArtifacts
    # helixRepo
    steps:
    - script: eng/common/cibuild.sh --projects $(Build.SourcesDirectory)/illink.sln /p:ArcadeBuild=true